# Generated by Django 4.0 on 2021-12-20 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='posts-image/', verbose_name='عکس')),
                ('description', models.TextField(max_length=300, verbose_name='توضیحات خلاصه')),
                ('status', models.PositiveSmallIntegerField(choices=[('d', 'پیش نویس'), ('p', 'در حال انتشار'), ('da', 'عدم تایید')], verbose_name='وضعیت')),
                ('category', models.SmallIntegerField(choices=[('s', 'علمی'), ('e', 'آموزشی'), ('n', 'خبری')], verbose_name='دسته بندی')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(verbose_name='متن دیدگاه')),
                ('status', models.CharField(choices=[('p', 'در حال بررسی'), ('a', 'مورد قبول'), ('r', 'عدم تایید')], max_length=1, verbose_name='وضعیت')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blog.post', verbose_name='پست')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment', to='accounts.profile', verbose_name='کاربر')),
            ],
        ),
    ]
