# Generated by Django 4.0 on 2021-12-26 13:06

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='media/posts-image/', verbose_name='عکس')),
                ('short_description', models.TextField(max_length=300, verbose_name='توضیحات خلاصه')),
                ('long_description', ckeditor.fields.RichTextField(max_length=5000, null=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('1', 'پیش نویس'), ('2', 'در حال انتشار'), ('0', 'عدم تایید')], default=1, max_length=1, verbose_name='وضعیت')),
                ('category', models.CharField(choices=[('1', 'علمی'), ('2', 'آموزشی'), ('0', 'خبری')], default=1, max_length=1, verbose_name='دسته بندی')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(verbose_name='متن دیدگاه')),
                ('status', models.CharField(choices=[('p', 'در حال بررسی'), ('a', 'مورد قبول'), ('r', 'عدم تایید')], max_length=1, verbose_name='وضعیت')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blog.post', verbose_name='پست')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment', to='accounts.profile', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
            },
        ),
    ]
