# Generated by Django 4.0 on 2021-12-26 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='پیوند یکتا')),
                ('bio', models.TextField(blank=True, help_text='توضیحات فردی', null=True, verbose_name='درباره ی من')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام خانوادگی')),
                ('phone_number', models.CharField(blank=True, help_text='11 رقم وارد کنید', max_length=11, null=True, verbose_name='شماره همرا')),
                ('age', models.CharField(blank=True, help_text='2رقم وارد کنید', max_length=2, null=True, verbose_name='سن')),
                ('job', models.CharField(blank=True, max_length=50, verbose_name='سمت شغلی')),
                ('date_employment', models.DateTimeField(auto_now_add=True)),
                ('date_user_updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('gender', models.CharField(blank=True, choices=[('m', 'آقا'), ('f', 'خانم')], max_length=1, null=True, verbose_name='جنسیت')),
                ('nc', models.CharField(blank=True, max_length=11, null=True, verbose_name='کدملی')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='ایمیل')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.user', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل ها',
            },
        ),
    ]
