# Generated by Django 4.0 on 2021-12-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_author',
            field=models.CharField(choices=[('m', 'بله'), ('f', 'خیر')], default='خیر', max_length=1, verbose_name='آیا نویسنده هستید'),
        ),
    ]
