# Generated by Django 4.0 on 2022-01-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='11 رقم وارد کنید', max_length=11, null=True, verbose_name='شماره همراه'),
        ),
    ]
