# Generated by Django 4.0 on 2021-12-20 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_at', models.DateTimeField(auto_now_add=True)),
                ('age', models.PositiveSmallIntegerField(verbose_name='')),
                ('nc', models.CharField(max_length=10, verbose_name='کدم= ملی')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='معرفی')),
                ('gender', models.CharField(choices=[('m', 'آقا'), ('f', 'خانم'), ('سایر', 'سایر')], max_length=4, verbose_name='جنسیت')),
                ('is_author', models.BooleanField(default=False, verbose_name='آیا نویسنده است')),
                ('upload_resume', models.FileField(upload_to='', verbose_name='فایل رزومه')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.user', verbose_name='کاربر')),
            ],
        ),
    ]
