# Generated by Django 4.0 on 2021-12-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name='سن'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nc',
            field=models.CharField(max_length=10, verbose_name='کد ملی'),
        ),
    ]
